# Tests for R/cpp11.R, which is generated ("do not edit by hand") and holds
# only thin .Call() wrappers around the compiled routines in src/. The
# behaviour of each routine is tested through its R-level wrapper
# (test_rrLassosum.R, test_rrPrsCs.R, test_rrSdpr.R, test_rrPenalizedRss.R,
# test_sumstatsQc.R for DENTIST, test_qtlEnrichmentPipeline.R).
#
# What is left to check here is the seam those tests cannot see: that every
# generated wrapper's native symbol is actually registered in the compiled
# library. Regenerating cpp11.R without rebuilding src/ -- or renaming a C++
# entry point and regenerating only one side -- leaves a wrapper whose .Call()
# target does not exist, and that surfaces at run time as an unhelpful
# "object '_pecotmr_x' not found" from deep inside a pipeline.

.cpp_wrappers <- c(
    "dentistIterativeImpute",
    "lassosumRssRcpp",
    "penalizedRssRcpp",
    "prsCsRcpp",
    "qtlEnrichmentRcpp",
    "sdprRcpp"
)

test_that("every generated cpp11 wrapper exists in the namespace", {
    ns <- asNamespace("pecotmr")
    for (nm in .cpp_wrappers) {
        expect_true(
            exists(nm, envir = ns, inherits = FALSE),
            label = str_c("cpp11 wrapper '", nm, "'")
        )
        expect_true(is.function(get(nm, envir = ns)))
    }
})

test_that("every cpp11 wrapper's native symbol is registered", {
    dll <- getLoadedDLLs()[["pecotmr"]]
    skip_if(is.null(dll), "pecotmr DLL not loaded in this run")
    registered <- names(getDLLRegisteredRoutines(dll)$.Call)
    skip_if(length(registered) == 0L, "no registered .Call routines visible")
    for (nm in .cpp_wrappers) {
        expect_true(
            str_c("_pecotmr_", nm) %in% registered,
            label = str_c("native symbol for '", nm, "'")
        )
    }
})

test_that("cpp11.R is not hand-edited away from its generated form", {
    src <- readLines(
        system.file(
            "..",
            "R",
            "cpp11.R",
            package = "pecotmr",
            mustWork = FALSE
        ),
        warn = FALSE
    )
    skip_if(length(src) == 0L, "R/cpp11.R not visible from this run")
    expect_match(src[[1L]], "Generated by cpp11")
    # Each wrapper body is a single .Call to its own `_pecotmr_<name>` symbol;
    # anything else means the file was edited by hand.
    declared <- str_match(src, "^([A-Za-z][A-Za-z0-9_.]*) <- function")[, 2]
    declared <- declared[!is.na(declared)]
    expect_setequal(declared, .cpp_wrappers)
    for (nm in declared) {
        expect_true(
            any(str_detect(src, fixed(str_c("`_pecotmr_", nm, "`")))),
            label = str_c("'", nm, "' calls its own native symbol")
        )
    }
})
