context:
  version: VERSION_PLACEHOLDER

package:
  name: r-pecotmr
  version: ${{ version }}

source:
  url: https://github.com/StatFunGen/pecotmr/archive/${{ version }}.tar.gz
  sha256: SHA256SUM_PLACEHOLDER

build:
  number: BUILD_PLACEHOLDER
  dynamic_linking:
    rpaths:
      - lib/R/lib/
      - lib/
  script: R CMD INSTALL --build .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - bioconductor-iranges
    - bioconductor-qvalue
    - bioconductor-snpstats
    - r-base
    - r-bigsnpr
    - r-bigstatsr
    - r-coloc
    - r-data.table
    - r-dofuture
    - r-dplyr
    - r-fsusier
    - r-furrr
    - r-gbj
    - r-ggplot2
    - r-ggnewscale
    - r-ggrepel
    - r-ggvenn
    - r-glmnet
    - r-harmonicmeanp
    - r-magrittr
    - r-matrixstats
    - r-mr.ash.alpha
    - r-mr.mash.alpha
    - r-mvsusier
    - r-pgenlibr
    - r-purrr
    - r-qgg
    - r-quadprog
    - r-quantreg
    - r-r.utils
    - r-r6
    - r-rcpp
    - r-readr
    - r-rfast
    - r-stringr
    - r-susier
    - r-tidyr
    - r-udr
    - r-vctrs
  run:
    - bioconductor-iranges
    - bioconductor-qvalue
    - bioconductor-snpstats
    - r-base
    - r-bigsnpr
    - r-bigstatsr
    - r-coloc
    - r-data.table
    - r-dofuture
    - r-dplyr
    - r-fsusier
    - r-furrr
    - r-gbj
    - r-ggplot2
    - r-ggnewscale
    - r-ggrepel
    - r-ggvenn
    - r-glmnet
    - r-harmonicmeanp
    - r-magrittr
    - r-matrixstats
    - r-mr.ash.alpha
    - r-mr.mash.alpha
    - r-mvsusier
    - r-pgenlibr
    - r-purrr
    - r-qgg
    - r-quadprog
    - r-quantreg
    - r-r.utils
    - r-r6
    - r-rcpp
    - r-readr
    - r-rfast
    - r-stringr
    - r-susier
    - r-tidyr
    - r-udr
    - r-vctrs

tests:
  - script:
      - R -e "library('pecotmr')"

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: pecotmr implements pair-wise enrichment, colocalization, TWAS and Mendelian Randomization to integrate QTL and GWAS analysis based on a fine-mapped single effects model.
  homepage: https://github.com/StatFunGen/pecotmr

extra:
  recipe-maintainers:
    - danielnachun
