name: osx-64

on:
  pull_request:
    paths:
      - 'recipe/build.sh'
      - 'recipe/meta.yaml'

jobs:
  build_packages:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: boa
          create-args: boa conda-verify
          generate-run-shell: true

      - name: Set up channels
        shell: micromamba-shell {0}
        run: |
          conda config --file /Users/runner/micromamba-bin/.condarc --append channels bioconda
          conda config --file /Users/runner/micromamba-bin/.condarc --append channels nodefaults
          xargs -I % conda config --file /Users/runner/micromamba-bin/.condarc --prepend channels % < .custom_channels
          conda config --show-sources

      - name: Build conda packages
        shell: micromamba-shell {0}
        run: conda mambabuild --output-folder /tmp/conda-bld recipe

      - name: Upload packages to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: packages_${{github.event.pull_request.head.sha}}_osx-64
          path: /tmp/conda-bld
